Create Table StaffInfo (
Subject VARCHAR(300) NOT NULL UNIQUE,
First_Name VARCHAR(300) NOT NULL,
Last_Name VARCHAR(300) NOT NULL,
DOB DATE NOT NULL,
NI_NUMBER CHAR(9) NOT NULL UNIQUE
);




ALTER TABLE StaffInfo
ADD POSTCODE VARCHAR(10) NOT NULL,
ADD SORTCODE CHAR(6) NOT NULL,
ADD ACCOUNT_NUMBER CHAR(8) NOT NULL UNIQUE;
